version: '3.8'
services:
  test-sprt:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '10.0'
          memory: 8g
    volumes:
      - ./output:/app/output
    command: ["1.0", "1.0-SNAPSHOT"] # Parameters for test_sprt.sh
